version: '1'
services:
  my-alpine:
    image: alpine:3.19.1
    volumes:
      - ./vols/alpine:/root/mnt
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8888
    entrypoint:
      - tail
      - -f
      - /dev/null
    networks:
      dev:
        ipv4_address: 172.31.0.3
  my-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./vols/postgres/:/var/lib/postgresql/data
    networks:
      dev:
        ipv4_address: 172.31.0.2
  my-redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    networks:
      dev:
        ipv4_address: 172.31.0.4
  my-prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - 9090:9090
    volumes:
      - ./vols/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      dev:
        ipv4_address: 172.31.0.5
  my-grafana:
    image: grafana/grafana:10.1.9-ubuntu
    ports:
      - 3000:3000
    volumes:
      - ./vols/grafana:/var/lib/grafana
    networks:
      dev:
        ipv4_address: 172.31.0.6
  my-gogs:
    image: gogs/gogs
    ports:
      - 10022:22
      - 10880:3000
    volumes:
      - ./vols/gogs:/data
    networks:
      dev:
        ipv4_address: 172.31.0.7
  my-jenkins:
    image: jenkins/jenkins:alpine3.19-jdk21
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./vols/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dev:
        ipv4_address: 172.31.0.8
  my-elasticsearch:
    image: elasticsearch:8.13.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      dev:
        ipv4_address: 172.31.0.9
  my-kibana:
    image: kibana:8.13.0
    ports:
      - 5601:5601
    networks:
      dev:
        ipv4_address: 172.31.0.10
  my-dokku:
    image: dokku/dokku:0.34.0
    ports:
      - 3022:22
      - 18080:80
      - 8443:443
    volumes:
      - ./vols/dokku:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOKKU_HOSTNAME=dokku.me
    networks:
      dev:
        ipv4_address: 172.31.0.11
networks:
  dev:
    name: dev-network
    external: true
